#!/usr/bin/env python3
"""Extract a real O3 calibration-uncertainty envelope for slide 17.

Source: LVK GWTC-3 parameter-estimation data release (Zenodo record 8177023),
event GW200322_091133 (O3b), analysis C01:IMRPhenomXPHM. Each detector's
``calibration_envelope`` is an (N, 7) array with columns:

    frequency (Hz), median mag, phase (rad),
    -1σ mag, -1σ phase (rad), +1σ mag, +1σ phase (rad)

(the same format as the GWTC-1 calibration envelope release, LIGO-P1900040).

We convert the amplitude to a percentage error, (mag - 1) * 100, and the phase
to degrees, and write the Hanford (H1) envelope as a JS module
(window.CALIBRATION_DATA) for the slide-17 figure.

Usage: python scripts/gen_calibration_data.py <path-to-PEDataRelease.h5>
Download the h5 (~21 MB) from:
  https://zenodo.org/records/8177023/files/IGWN-GWTC3p0-v2-GW200322_091133_PEDataRelease_mixed_cosmo.h5
"""

from __future__ import annotations

import json
import math
import sys
import warnings
from pathlib import Path

import numpy as np

warnings.filterwarnings("ignore")
import h5py  # noqa: E402

ANALYSIS = "C01:IMRPhenomXPHM"
DETECTOR = "H1"
N_OUT = 150


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit("usage: gen_calibration_data.py <PEDataRelease.h5>")
    src = sys.argv[1]
    with h5py.File(src, "r") as f:
        env = np.asarray(f[f"{ANALYSIS}/calibration_envelope/{DETECTOR}"])

    freq = env[:, 0]
    # Log-spaced resample within the released band.
    lo, hi = freq.min(), freq.max()
    grid = np.geomspace(lo, hi, N_OUT)

    def interp(col):
        return np.interp(np.log10(grid), np.log10(freq), env[:, col])

    med_mag, ph_med = interp(1), interp(2)
    lo_mag, lo_ph = interp(3), interp(4)
    hi_mag, hi_ph = interp(5), interp(6)

    deg = 180.0 / math.pi
    amp = [
        {
            "f": round(float(g), 3),
            "med": round(float((m - 1) * 100), 4),
            "lo": round(float((l - 1) * 100), 4),
            "hi": round(float((h - 1) * 100), 4),
        }
        for g, m, l, h in zip(grid, med_mag, lo_mag, hi_mag)
    ]
    phase = [
        {
            "f": round(float(g), 3),
            "med": round(float(m * deg), 4),
            "lo": round(float(l * deg), 4),
            "hi": round(float(h * deg), 4),
        }
        for g, m, l, h in zip(grid, ph_med, lo_ph, hi_ph)
    ]

    data = {
        "source": (
            "LVK GWTC-3 PE data release (Zenodo 8177023), GW200322_091133 "
            f"[O3b], {ANALYSIS}"
        ),
        "detector": "Advanced LIGO Hanford (O3b)",
        "fMin": round(float(lo), 3),
        "fMax": round(float(hi), 3),
        "amp": amp,
        "phase": phase,
    }
    out = Path(__file__).resolve().parent.parent / "js" / "calibration-data.js"
    banner = (
        "// AUTO-GENERATED by scripts/gen_calibration_data.py -- do not edit by hand.\n"
        "// Real O3b calibration-uncertainty envelope (LVK GWTC-3, GW200322).\n"
    )
    out.write_text(
        f"{banner}window.CALIBRATION_DATA = {json.dumps(data)}\n", encoding="utf-8"
    )

    amp_max = max(abs(a["lo"]) for a in amp) + max(abs(a["hi"]) for a in amp)
    ph_max = max(abs(p["lo"]) for p in phase) + max(abs(p["hi"]) for p in phase)
    kib = round(out.stat().st_size / 1024)
    print(f"Wrote {out.relative_to(Path.cwd())} ({kib} KiB)")
    print(f"  band {lo:.1f}-{hi:.1f} Hz; amp band up to ~{amp_max/2:.1f}%, phase up to ~{ph_max/2:.1f} deg")


if __name__ == "__main__":
    main()
