#!/usr/bin/env python3
"""Generate the frequency-vs-time chirp track used by slide 8's animation.

The message of slide 8 is the transition from the current generation of
detectors to the Einstein Telescope: because ET reaches down to much lower
frequencies, the *same* inspiral spends far longer in band and is therefore
seen much earlier before merger. This is a quantitative, data-backed story.

We use pycbc to produce the data:

* ``get_waveform_filter_length_in_time`` returns, for a given lower frequency
  cut-off, how long the inspiral template lasts before merger. Evaluated over a
  grid of frequencies this *is* the frequency-vs-time-before-merger track of the
  chirp (the point at which the inspiral sweeps through frequency ``f`` happens
  ``t(f)`` seconds before merger).
* We evaluate the same function at the representative low-frequency walls of the
  current detector network and of ET to get the "seen this long before merger"
  numbers annotated on the slide.

The output is written as a small JS module (``js/gw-chirp-data.js``) exposing
``window.GW_CHIRP_DATA`` so the animation needs no async fetch and survives the
``gulp build`` copy step (which already copies ``js/``).
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np

# pycbc emits a few SyntaxWarnings from docstrings on import; keep output clean.
warnings.filterwarnings("ignore", category=SyntaxWarning)

import pycbc  # noqa: E402
from pycbc.waveform import get_waveform_filter_length_in_time  # noqa: E402

# Canonical binary neutron star, the textbook multi-messenger / early-warning
# source. Its long inspiral makes the low-frequency reach of ET tangible.
APPROXIMANT = "TaylorF2"
MASS1 = 1.4
MASS2 = 1.4

# Representative low-frequency walls (Hz).
CURRENT_F_LOW = 20.0  # Advanced LIGO / Virgo sensitivity wall
ET_F_LOW = 3.0  # Einstein Telescope design low-frequency reach

# Frequency grid for the chirp track (log-spaced), from below the ET wall up to
# the late inspiral.
F_MIN = 2.0
F_MAX = 500.0
N_POINTS = 90


def chirp_time(f_low: float) -> float:
    """Seconds before merger at which the inspiral sweeps through ``f_low``."""
    return float(
        get_waveform_filter_length_in_time(
            APPROXIMANT,
            mass1=MASS1,
            mass2=MASS2,
            f_lower=f_low,
        )
    )


def main() -> None:
    freqs = np.geomspace(F_MIN, F_MAX, N_POINTS)
    track = [{"f": round(float(f), 4), "t": round(chirp_time(f), 4)} for f in freqs]

    bands = {
        "current": {
            "f_low": CURRENT_F_LOW,
            "t": round(chirp_time(CURRENT_F_LOW), 3),
            "label": "Current detectors",
            "sub": "Advanced LIGO / Virgo",
        },
        "et": {
            "f_low": ET_F_LOW,
            "t": round(chirp_time(ET_F_LOW), 3),
            "label": "Einstein Telescope",
            "sub": "low-frequency reach",
        },
    }

    data = {
        "source": (
            f"BNS {MASS1}+{MASS2} Msun inspiral, {APPROXIMANT} "
            f"(pycbc {pycbc.__version__})"
        ),
        "mass1": MASS1,
        "mass2": MASS2,
        "approximant": APPROXIMANT,
        "track": track,
        "bands": bands,
    }

    out = Path(__file__).resolve().parent.parent / "js" / "gw-chirp-data.js"
    payload = json.dumps(data, indent=2)
    banner = (
        "// AUTO-GENERATED by scripts/gen_gw_chirp_data.py -- do not edit by hand.\n"
        "// Frequency-vs-time chirp track produced with pycbc; see that script.\n"
    )
    out.write_text(f"{banner}window.GW_CHIRP_DATA = {payload}\n", encoding="utf-8")

    ratio = bands["et"]["t"] / bands["current"]["t"]
    print(f"Wrote {out.relative_to(Path.cwd())}")
    print(f"  source: {data['source']}")
    print(f"  current (f_low={CURRENT_F_LOW} Hz): {bands['current']['t']:.1f} s before merger")
    print(f"  ET      (f_low={ET_F_LOW} Hz): {bands['et']['t']:.1f} s before merger")
    print(f"  ET sees the same inspiral ~{ratio:.0f}x longer")


if __name__ == "__main__":
    main()
