#!/usr/bin/env python3
"""Generate detector sensitivity (ASD) curves for slide 12 ("Why low frequency").

Uses the community-standard reference sensitivity curves from LIGO-T1500293
("Unofficial sensitivity curves (ASD) for aLIGO, KAGRA, Virgo, Voyager, Cosmic
Explorer, and Einstein Telescope", curves_Jan_2020). These amplitude spectral
density files are the curves routinely used in the literature to compare current
and next-generation ground-based detectors. The .txt files are vendored under
``scripts/sensitivity_curves/`` so this is reproducible offline.

The message of the slide is the low-frequency end: the current generation walls
off around ~10-20 Hz, while the next generation (especially the underground
Einstein Telescope) reaches down toward a few Hz.

Output is a JS module (window.SENSITIVITY_DATA), matching the delivery pattern of
the other generated data modules.

Source: LIGO-T1500293, https://dcc.ligo.org/LIGO-T1500293/public
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

SRC = Path(__file__).resolve().parent / "sensitivity_curves"

# Which curves to show, in draw order, grouped by generation.
CURVES = [
    {"file": "aligo_design", "label": "Advanced LIGO", "gen": "current", "color": "#4a6b8a"},
    {"file": "advirgo", "label": "Advanced Virgo", "gen": "current", "color": "#7189a0"},
    {"file": "kagra", "label": "KAGRA", "gen": "current", "color": "#9fb0bf"},
    {"file": "et_d", "label": "Einstein Telescope", "gen": "future", "color": "#00a5c8"},
    {"file": "ce2", "label": "Cosmic Explorer", "gen": "future", "color": "#f2a900"},
]

F_MIN = 1.5
F_MAX = 5000.0
N_POINTS = 200
# Display ceiling: above this ASD a detector has effectively walled off. Trimming
# there makes each curve end cleanly at its low-frequency wall instead of
# shooting to ~1e-17 and blowing up the vertical scale.
ASD_MAX = 1.0e-21


def resample(path: Path) -> list[dict]:
    raw = np.loadtxt(path)
    f, asd = raw[:, 0], raw[:, 1]
    ok = (f > 0) & (asd > 0)
    f, asd = f[ok], asd[ok]
    order = np.argsort(f)
    f, asd = f[order], asd[order]

    lo = max(F_MIN, f.min())
    hi = min(F_MAX, f.max())
    grid = np.geomspace(lo, hi, N_POINTS)
    logasd = np.interp(np.log10(grid), np.log10(f), np.log10(asd))
    vals = 10.0**logasd

    pts = [
        {"f": round(float(g), 4), "asd": float(f"{a:.4e}")}
        for g, a in zip(grid, vals)
        if a <= ASD_MAX
    ]
    return pts


def main() -> None:
    curves = []
    for spec in CURVES:
        pts = resample(SRC / f"{spec['file']}.txt")
        f_low = pts[0]["f"] if pts else None
        curves.append(
            {
                "label": spec["label"],
                "gen": spec["gen"],
                "color": spec["color"],
                "points": pts,
                "f_low": f_low,
            }
        )
        print(f"  {spec['label']:<20} {len(pts)} pts, from {f_low:.2f} Hz")

    data = {
        "source": "LIGO-T1500293 reference sensitivity curves (curves_Jan_2020)",
        "curves": curves,
    }
    out = Path(__file__).resolve().parent.parent / "js" / "sensitivity-data.js"
    banner = (
        "// AUTO-GENERATED by scripts/gen_sensitivity_data.py -- do not edit by hand.\n"
        "// Detector ASD curves from LIGO-T1500293 (dcc.ligo.org/LIGO-T1500293).\n"
    )
    out.write_text(
        f"{banner}window.SENSITIVITY_DATA = {json.dumps(data)}\n", encoding="utf-8"
    )
    kib = round(out.stat().st_size / 1024)
    print(f"Wrote {out.relative_to(Path.cwd())}  ({kib} KiB)")


if __name__ == "__main__":
    main()
