#!/usr/bin/env python3
"""Bake the matched-filter search animation data for slide 21.

Source: the ET null-stream/background project's baked search data
(scripts/matched_filter_search.json), produced by its et_ns_pipeline — two real
CBC signals injected in both detectors, real coloured ET noise, and a genuine
matched-filter SNR(t). We downsample and keep only what the slide-21 animation
needs (two-detector strain, the max-over-bank matched-filter SNR ρ(t), the
threshold, the triggers, and one template glyph), and write it as a JS module
(window.MATCHED_FILTER_DATA).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

SRC = Path(__file__).resolve().parent / "matched_filter_search.json"
TEMPLATES = ["Ta", "Tb", "Tc"]


def ds(arr, step):
    return [round(float(v), 4) for v in np.asarray(arr)[::step]]


def main() -> None:
    d = json.loads(SRC.read_text())

    x = np.asarray(d["strain"]["x"])
    sstep = 2  # 1100 -> ~550
    strain = {
        "x": ds(x, sstep),
        "d1": ds(d["strain"]["d1"], sstep),
        "d2": ds(d["strain"]["d2"], sstep),
    }

    t = np.asarray(d["rho"]["_t"])
    rho1 = np.maximum.reduce([np.asarray(d["rho"][f"d1:{k}"]) for k in TEMPLATES])
    rho2 = np.maximum.reduce([np.asarray(d["rho"][f"d2:{k}"]) for k in TEMPLATES])
    rho = {
        "t": [round(float(v), 4) for v in t],
        "d1": [round(float(v), 3) for v in rho1],
        "d2": [round(float(v), 3) for v in rho2],
    }

    tmpl = ds(d["bank"][0]["shape"], 3)  # one chirp glyph for the scanning cursor

    out_data = {
        "source": d.get("provenance", {}).get("physics", ""),
        "note": d.get("provenance", {}).get("note", ""),
        "tMin": round(float(x.min()), 3),
        "tMax": round(float(x.max()), 3),
        "thr": d["thr"],
        "strain": strain,
        "rho": rho,
        "triggers": d["triggers"],
        "template": tmpl,
    }

    out = Path(__file__).resolve().parent.parent / "js" / "matched-filter-data.js"
    banner = (
        "// AUTO-GENERATED by scripts/gen_matched_filter_data.py -- do not edit by hand.\n"
        "// Real matched-filter search data (two-detector strain + genuine MF SNR).\n"
    )
    out.write_text(
        f"{banner}window.MATCHED_FILTER_DATA = {json.dumps(out_data)}\n",
        encoding="utf-8",
    )
    kib = round(out.stat().st_size / 1024)
    print(f"Wrote {out.relative_to(Path.cwd())} ({kib} KiB)")
    print(f"  strain {len(strain['x'])} pts, rho {len(rho['t'])} pts, thr={out_data['thr']}")
    print(f"  triggers d1={d['triggers']['d1']}")


if __name__ == "__main__":
    main()
