#!/usr/bin/env node
// Generate a bundled Europe GeoJSON for the slide-11 candidate-site map.
//
// Source: world-atlas countries-110m (Natural Earth, public domain), converted
// from TopoJSON to GeoJSON with topojson-client and filtered to a Europe
// bounding box so the deck stays small and fully offline. Output is written as
// a JS module (window.EUROPE_GEO), matching the delivery pattern of the other
// generated data modules.

const fs = require('fs')
const path = require('path')
const topojson = require('topojson-client')
const world = require('world-atlas/countries-110m.json')

// Bounding box of the region shown on the slide (lon/lat).
const BBOX = { west: -12, east: 32, south: 34, north: 60 }

const fc = topojson.feature(world, world.objects.countries)

function inBox(feature) {
    // Keep a country if any coordinate falls within the display bbox.
    let hit = false
    const scan = (coords) => {
        if (hit) return
        if (typeof coords[0] === 'number') {
            const [lon, lat] = coords
            if (
                lon >= BBOX.west &&
                lon <= BBOX.east &&
                lat >= BBOX.south &&
                lat <= BBOX.north
            ) {
                hit = true
            }
            return
        }
        for (const c of coords) scan(c)
    }
    scan(feature.geometry.coordinates)
    return hit
}

const features = fc.features.filter(inBox)

// Round coordinates to 3 decimals (~100 m) to shrink the file.
const round = (coords) => {
    if (typeof coords[0] === 'number') {
        return [
            Math.round(coords[0] * 100) / 100,
            Math.round(coords[1] * 100) / 100,
        ]
    }
    return coords.map(round)
}
for (const f of features) {
    f.geometry.coordinates = round(f.geometry.coordinates)
    // Drop bulky properties; we only need the outlines.
    f.properties = {}
    delete f.id
}

const out = { type: 'FeatureCollection', features }
const dest = path.resolve(__dirname, '..', 'js', 'europe-geo.js')
const banner =
    '// AUTO-GENERATED by scripts/gen_europe_geo.js -- do not edit by hand.\n' +
    '// Europe country outlines (Natural Earth 110m via world-atlas, public domain).\n'
fs.writeFileSync(dest, `${banner}window.EUROPE_GEO = ${JSON.stringify(out)}\n`)

const kib = Math.round(fs.statSync(dest).size / 1024)
console.log(`Wrote js/europe-geo.js  (${features.length} features, ${kib} KiB)`)
